replicaCount: 2

image:
  repository: "<your-registry>/<your-java-app-image>"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources: {}
